version: '3'

services:
  db:
    image: mysql
    container_name: cat-nest-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis
    container_name: cat-nest-redis
    restart: always
    ports:
      - "6379:6379"
  nacos:
    image: nacos/nacos-server:v2.2.0
    container_name: cat-nest-nacos
    restart: always
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"

networks:
  cat-nest:
