server:
  port: 8081
  servlet:
    context-path: /system



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:log/logback-conf.xml

spring:
  application:
    name: cat-nest-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.117.131:3306/cat-nest-system
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
  cloud:
    nacos:
      server-addr: localhost:8848


cat-nest:
  datasource:
    securityKey: 12345678habcdefg


