server:
  port: 8081
  servlet:
    context-path: /system


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat-nest-system
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379



