server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: file
          uri: http://localhost:8083
          predicates:
            - Path=/file/**
        - id: system
          uri: http://localhost:8081
          predicates:
            - Path=/system/**
